name: Build release zip

on:
  workflow_dispatch

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build plugin # modify this step as needed
      run: |
        composer install --no-dev
        composer build wp2static.zip

    - name: Upload the archive as an artifact
      id: upload-plugin-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: $HOME/Downloads

    
