name: Build release zip

on:
  workflow_dispatch

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build plugin # Remove or modify this step as needed
      run: |
        composer install --no-dev
        npm install
        npm run build

    - name: Generate zip
      uses: 10up/action-wordpress-plugin-build-zip@v1.0.1
      with:
        retention-days: 5 # Optional; defaults to 5
